ExternalProject_Add(Raylib
  GIT_REPOSITORY "https://github.com/raysan5/raylib"
  GIT_TAG "4.2.0"
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/third_party/raylib
  BINARY_DIR ${CMAKE_BINARY_DIR}/RaylibBuild
  CMAKE_CACHE_ARGS
    -DCUSTOMIZE_BUILD:BOOL=1
    -DSUPPORT_EVENTS_WAITING:BOOL=1
    -DSUPPORT_FILEFORMAT_GIF:BOOL=1
    -DSUPPORT_FILEFORMAT_TGA:BOOL=1
    -DSUPPORT_FILEFORMAT_QOI:BOOL=1
    -DSUPPORT_FILEFORMAT_FLAC:BOOL=1
    -DSUPPORT_FILEFORMAT_JPG:BOOL=1
    -DOPENGL_VERSION:STRING="2.1"
  INSTALL_COMMAND ""
  )
